version: "3.8"

services:
  backend:
    container_name: horus-backend
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=my-influx-token
      - INFLUX_ORG=horus-org
      - INFLUX_BUCKET=horus-bucket
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=horus
      - POSTGRES_USER=horus_user
      - POSTGRES_PASSWORD=horus_pass
    depends_on:
      - influxdb
      - postgres
    restart: unless-stopped

  influxdb:
    container_name: horus-influxdb
    image: influxdb:2.7.5
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=horus-org
      - DOCKER_INFLUXDB_INIT_BUCKET=horus-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-influx-token
    volumes:
      - influxdb_data:/var/lib/influxdb2
    restart: unless-stopped

  postgres:
    container_name: horus-postgres
    image: postgres:15.6
    environment:
      POSTGRES_DB: horus
      POSTGRES_USER: horus_user
      POSTGRES_PASSWORD: horus_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  grafana:
    container_name: horus-grafana
    image: grafana/grafana:11.3.0
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./frontend/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./frontend/grafana/dashboards:/var/lib/grafana/dashboards:ro
    restart: unless-stopped

  edge_sim:
    container_name: horus-edge-sim
    build:
      context: .
      dockerfile: edge/Dockerfile
    environment:
      - BACKEND_URL=http://backend:8000/ingest
      - INTERVAL=5
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  influxdb_data:
  pgdata:
  grafana_data:
